export const Database = {
  dashboard: 'dashboard',
  galleries: 'galleries',
  users: 'users',
  usersInfo: 'users_info',
  userRoles: 'user_roles',
  roles: 'roles',
  permissions: 'permissions',
  permissionTypes: 'permission_types',
  rolePermissions: 'role_permissions',
  products: 'products',
  productVariations: 'product_variations',
  productCategories: 'product_categories',
  dosageForms: 'dosage_forms',
  generics: 'generics',
  suppliers: 'suppliers',
  categories: 'categories',
  orders: 'orders',
  orderReturns: 'order_returns',
  deliveryServiceTypes: 'delivery_service_types',
  deliveryZones: 'delivery_zones',
  coupons: 'coupons',
  paymentMethods: 'payment_methods',
  transactions: 'transactions',
  banners: 'banners',
  features: 'features',
  settings: 'settings',
};
