export enum ENUM_ORDER_STATUS_TYPES {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  PROCESSING = 'PROCESSING',
  SHIPPED = 'SHIPPED',
  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
  // RETURNED = 'RETURNED',
}

export type TOrderStatusType = `${ENUM_ORDER_STATUS_TYPES}`;
export const orderStatusTypes: TOrderStatusType[] = Object.values(ENUM_ORDER_STATUS_TYPES);

export enum ENUM_ORDER_PAYMENT_STATUS_TYPES {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  PARTIALLY_PAID = 'PARTIALLY_PAID',
  PAID = 'PAID',
  FAILED = 'FAILED',
  // REFUNDED = 'REFUNDED',
  // PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED',
  CANCELLED = 'CANCELLED',
}

export type TOrderPaymentStatusType = `${ENUM_ORDER_PAYMENT_STATUS_TYPES}`;
export const orderPaymentStatusTypes: TOrderPaymentStatusType[] = Object.values(ENUM_ORDER_PAYMENT_STATUS_TYPES);
